config/routes.rb
Rails.application.routes.draw do
  # Deviseのルートを追加
  devise_for :users, controllers: { invitations: 'devise/invitations' }

  # アプリケーションのルートを定義
  root "thanks#index"

  # Thanksリソースのルートを定義
  resources :thanks, except: [ :new, :edit ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invitation.rb
class Invitation < ApplicationRecord
end

app/models/thank.rb
class Thank < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :thanks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Modern browser support (省略しても大丈夫です)
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:invite, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:accept_invitation, keys: [:password, :password_confirmation, :invitation_token, :name])
  end

  # ログイン後のリダイレクト
  def after_sign_in_path_for(resource_or_scope)
    flash[:notice] = "ログインに成功しました"
    root_path
  end

  # ログアウト後のリダイレクト
  def after_sign_out_path_for(resource_or_scope)
    flash[:alert] = "ログアウトしました"
    root_path
  end

  # サインアップ後のリダイレクト
  def after_sign_up_path_for(resource_or_scope)
    flash[:notice] = "サインアップしました"
    root_path
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new(invitation_params)
    if @invitation.save
      InvitationMailer.send_invitation(@invitation).deliver_now
      redirect_to  root_path, notice: '招待メールが送信されました'
    else
      render :new
    end
  end

  private

  def invitation_params
    params.require(:invitation).permit(:email)
  end
end

app/controllers/thanks_controller.rb
class ThanksController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create, :destroy ]
  before_action :set_thank, only: [ :edit, :update, :destroy ]

  def index
    if current_user
      @thanks = current_user.thanks.order(date: :desc)
      @thanks_json = @thanks.to_json
      puts "Debug: @thanks_json = #{@thanks_json}" # デバッグ用

    else
      @thanks = []
      @thanks_json = [].to_json
    end
  end

  def new
    @thank = Thank.new
  end

  def create
    @thank = current_user.thanks.new(thank_params)
    if @thank.save
      redirect_to thanks_path, notice: "感謝しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @thank.update(thank_params)
      redirect_to thanks_path, notice: "更新されました"
    else
      render :edit
    end
  end

  def destroy
    @thank.destroy
    redirect_to thanks_path, notice: "削除されました"
  end

  private

  def set_thank
    @thank = current_user.thanks.find(params[:id])
  end

  def thank_params
    params.require(:thank).permit(:category, :content, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/thanks_helper.rb
module ThanksHelper
end

app/views/invitations/create.html.erb
<h1>Invitations#create</h1>
<p>Find me in app/views/invitations/create.html.erb</p>

app/views/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <% resource.class.invite_key_fields.each do |field| -%>
    <div class="field">
      <%= f.label field %><br />
      <%= f.text_field field %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit t("devise.invitations.new.submit_button") %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "感謝日記" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script>
      window.currentUser = <%= user_signed_in? ? 'true' : 'false' %>;
    </script>
  </head>

  <body>
    <%# <div id="thanks_app"></div> %>

    <div id="flash-messages" class="container mx-auto mt-4 px-4" data-turbo="false">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> bg-blue-100 border-l-4 border-blue-500 text-blue-700 p-4 mb-4">
          <%= value %>
        </div>
      <% end %>
    </div>
    
    <%= yield %>
  </body>
</html>

app/views/thanks/index.html.erb
<%= content_for :head do %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
<% end %>

<div id="thanks_app" data-thanks="<%= @thanks_json %>"></div>

<!-- 招待するボタン -->
<div class="invite-button-container">
  <%= link_to '招待する', new_user_invitation_path, class: "btn btn-primary" %>
</div>

<script>
  console.log('Rails data:', <%= raw @thanks_json %>);
</script>